### ISSUE TITLE
Disable warning that executable `gtm` does not exist

### ISSUE THREAD

**Issue by niklaas** [git-time-metric/gtm-vim-plugin#5]
I use `vim` on more machines that I use `gtm`. So `gtm` isn't always installed. Is there some way to silent the annoying complaint that `gtm` cannot be found when `vim` is started?

**Comment by mschenk42** [comment]
In you .vimrc you can check if the executable exists before loading the plugin.

I use vim-plug to manage my plugins.
```
if executable('gtm')
   Plug 'git-time-metric/gtm-vim-plugin'
endif
```

**Comment by niklaas** [comment]
Of course! I have this in my `.vimrc` anyway:

```vim
" Conditional activation for vim-plug plugins
" https://github.com/junegunn/vim-plug/wiki/tips#conditional-activation
function! Cond(cond, ...)
  let opts = get(a:000, 0, {})
  return a:cond ? opts : extend(opts, { 'on': [], 'for': [] })
endfunction
```

So it's as simple as

```vim
Plug 'git-time-metric/gtm-vim-plugin', Cond(executable('gtm'))
```

Could have come up with that myself. Thank you!
